{
 "title": "CombatSimulation",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Sevrielle's Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "HP" }
   ],
   "targets": [
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "characters",
     "select": [
      [
       { "params": [ "hp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "characterName", "operator": "=", "value": "Sevrielle" }
     ]
    },
    {
     "alias": "Mana",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "characters",
     "select": [
      [
       { "params": [ "mana" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "characterName", "operator": "=", "value": "Sevrielle" }
     ]
    }
   ]
  },
  {
   "title": "Ursoc's Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "HP" }
   ],
   "targets": [
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "characters",
     "select": [
      [
       { "params": [ "hp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "characterName", "operator": "=", "value": "Ursoc" }
     ]
    },
    {
     "alias": "Mana",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "characters",
     "select": [
      [
       { "params": [ "mana" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "characterName", "operator": "=", "value": "Ursoc" }
     ]
    }
   ]
  },
  {
   "title": "Murloc 1's Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "HP" }
   ],
   "targets": [
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "characters",
     "select": [
      [
       { "params": [ "hp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "characterName", "operator": "=", "value": "Murloc 1" }
     ]
    },
    {
     "alias": "Rage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "characters",
     "select": [
      [
       { "params": [ "rage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "characterName", "operator": "=", "value": "Murloc 1" }
     ]
    }
   ]
  },
  {
   "title": "Murloc 2's Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "HP" }
   ],
   "targets": [
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "characters",
     "select": [
      [
       { "params": [ "hp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "characterName", "operator": "=", "value": "Murloc 2" }
     ]
    },
    {
     "alias": "Rage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "characters",
     "select": [
      [
       { "params": [ "rage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "characterName", "operator": "=", "value": "Murloc 2" }
     ]
    }
   ]
  },
  {
   "title": "Move History",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "Value",
     "measurement": "moves",
     "select": [
      [
       { "params": [ "caster" ], "type": "field" }
      ],
      [
       { "params": [ "moveName" ], "type": "field" }
      ],
      [
       { "params": [ "type" ], "type": "field" }
      ],
      [
       { "params": [ "value" ], "type": "field" }
      ],
      [
       { "params": [ "target" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Event History",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "measurement": "events",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "player" ], "type": "field" }
      ],
      [
       { "params": [ "description" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}